### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by asnazevedo** [hugodias/CakeStrap-Manager-Module#1]
Ola Hugo...
Estou interessado em utilizar o gerenciador mas não encontrei nenhum material  de como utilizá-lo...
você tem algum tutorial?

**Comment by hugodias** [comment]
Ola @asnazevedo , basta seguir o [Readme](https://github.com/hugodias/CakeStrap-Manager-Module/blob/master/README.md) do respositório, não tem mistério. Depois de incluir o plugin e criar as tabelas basta acessar o link http://seuapp/gerenciador que o plugin será acessado.

Para modificar o código basta acessar os arquivos em app/Plugin/Gerenciador !
